Run and save meta data saving.
toolsforexperiments/labcore-old pull request #11
Opened 2021-09-13 21:54 UTC by pfafflabatuiuc

Added the ability to save meta-data with the run_and_save_sweep() function. The function accepts any kwargs and will try to save it. The names of the files are the keys of the kwargs.

If a kwarg is a dictionary, it will try to save it as a json file. If it fails and detects that an ndarray is present as one of its values, it will transform it into a list. After trying, if it still fails, the dictionary will be pickled and saved.

Any other object passed will be pickled and saved. If an object is passed that cannot be pickled, the function will print a warning saying that the item was not able to be saved, but it will still run and save the sweep.

A few things I would like to have feedback:

- The whole try and save as a dictionary, convert and try again might be a little bit too complicated and could be simplified if either we just save everything as a pickle, or try to save a json once instead of converting and trying again.
- When trying to save to JSON but it fails, a file is still created with missing data. I could not properly figure out what objects get saved and which ones don't when this happens, so to not save extra dead files I manually delete them.
- General code style.

2021-09-14 00:07 UTC, wpfff commented
let's look at the code together before merging.

2021-09-14 00:11 UTC, wpfff requested changes
i think it would be cleaner to analyze the metadata for specific characteristics rather than doing everything with try/except blocks.
my approach would be:
- copy the dictionary
- walk through the data and convert things that need to be converted
- try to save
- only if that fails, pickle it

2021-09-14 00:11 UTC, wpfff commented on labcore/ddh5.py
> +            pickle_directory = dir + '\\' + key + '.pickle'
always use os.path.join for making paths.

2021-09-14 00:11 UTC, wpfff commented on labcore/ddh5.py
> +                dictionary_directory = dir + '\\' + key + '.json'
see above.

2021-09-15 14:32 UTC, wpfff requested changes

2021-09-15 14:32 UTC, wpfff commented on labcore/ddh5.py
> +            pickle_directory = os.path.join(dir, key + '.pickle')
better naming here... this is not a directory, but a filepath, right?

2021-09-15 14:32 UTC, wpfff commented on labcore/ddh5.py
> +                    _save_dictionary(value, dictionary_directory)
see above.

2021-09-15 14:32 UTC, wpfff commented on labcore/ddh5.py
> +                    for k, v in value.items():
why are you converting and then saving to pickle?
i thought the whole point of converting to list was that we can save as json?

2021-09-15 23:19 UTC, pfafflabatuiuc commented on labcore/ddh5.py
> +                    for k, v in value.items():
This was a mistake. It is corrected now. Will write tests for it tomorrow.

2021-09-18 03:54 UTC, merged